// ------------------------------------------------------------
// Copyright (c) Bartels Online.  All rights reserved.
// ------------------------------------------------------------

using System.Collections.Generic;
using System.Linq;
using System.Text.Json;
using System.Text.Json.Serialization;

namespace GISBlox.Services.SDK.Models
{
   /// <summary>
   /// Represents the result of an audience analysis based on key figures of postal codes.
   /// </summary>
   /// <remarks>This class provides structured access to both raw and calculated data from an audience analysis
   /// operation. It exposes collections for per-postal code figures, overall summaries, recalculated percentages,
   /// weighted averages, derived insights, and a persona description. The data can be accessed in object form or
   /// serialized to JSON for interoperability with other systems.</remarks>
   public sealed class AudienceAnalysisResult
   {
      private static readonly JsonSerializerOptions _jsonSerializerOptions = new()
      {
         DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull
      };

      private List<Dictionary<string, JsonElement>> _items = [];
      private Dictionary<string, JsonElement> _summary = [];
      private Dictionary<string, JsonElement> _percentages = [];
      private Dictionary<string, JsonElement> _averages = [];
      private Dictionary<string, JsonElement> _insights = [];
      private Dictionary<string, JsonElement> _persona = [];

      /// <summary>
      /// Contains the key figures of each postal code in the result set.
      /// </summary>
      public List<Dictionary<string, object>> Items
      {
         get => [.. _items.Select(ToTypedDictionary)];
         set => _items = value?.Select(ToJsonElementDictionary).ToList() ?? [];
      }

      /// <summary>
      /// Represents the totals of the key figures across all postal codes in the result set. 
      /// </summary>
      public Dictionary<string, object> Summary
      {
         get => ToTypedDictionary(_summary);
         set => _summary = ToJsonElementDictionary(value);
      }

      /// <summary>
      /// Represents the recalculated percentages of the key figures across all postal codes in the result set, based on the totals in the Summary property.
      /// </summary>
      public Dictionary<string, object> Percentages
      {
         get => ToTypedDictionary(_percentages);
         set => _percentages = ToJsonElementDictionary(value);
      }

      /// <summary>
      /// Represents the weighted averages of the key figures across all postal codes in the result set.       
      /// </summary>
      public Dictionary<string, object> Averages
      {
         get => ToTypedDictionary(_averages);
         set => _averages = ToJsonElementDictionary(value);
      }

      /// <summary>
      /// Represents the derived audience scores based on the key figures across all postal codes in the result set. 
      /// These scores are generated by applying predefined rules and thresholds to the key figures. 
      /// </summary>
      public Dictionary<string, object> Insights
      {
         get => ToTypedDictionary(_insights);
         set => _insights = ToJsonElementDictionary(value);
      }

      /// <summary>
      /// Objective, source data-driven description of the audience segment that is identified in the result set. 
      /// </summary>
      public Dictionary<string, object> Persona
      {
         get => ToTypedDictionary(_persona);
         set => _persona = ToJsonElementDictionary(value);
      }

      /// <summary>
      /// Converts the current object to a JsonDocument.
      /// </summary>
      /// <returns>A JsonDocument that represents the current object in JSON format.</returns>
      public JsonDocument ToJson()
      {
         return JsonSerializer.SerializeToDocument(this, _jsonSerializerOptions);
      }

      /// <summary>
      /// Converts the current object to its JSON string representation.
      /// </summary>      
      /// <returns>A JSON-formatted string that represents the current object.</returns>
      public string ToJsonString()
      {
         return JsonSerializer.Serialize(this, _jsonSerializerOptions);
      }

      private static Dictionary<string, object> ToTypedDictionary(Dictionary<string, JsonElement> source)
      {
         return source.ToDictionary(kvp => kvp.Key, kvp => ToValue(kvp.Value));
      }

      private static Dictionary<string, JsonElement> ToJsonElementDictionary(Dictionary<string, object> source)
      {
         return source?.ToDictionary(kvp => kvp.Key, kvp => JsonSerializer.SerializeToElement(kvp.Value, _jsonSerializerOptions)) ?? [];
      }

      private static object ToValue(JsonElement element)
      {
         return element.ValueKind switch
         {
            JsonValueKind.Object => element.EnumerateObject().ToDictionary(p => p.Name, p => ToValue(p.Value)),
            JsonValueKind.Array => element.EnumerateArray().Select(ToValue).ToList(),
            JsonValueKind.String when element.TryGetDateTime(out var dateTime) => dateTime,
            JsonValueKind.String => element.GetString(),
            JsonValueKind.Number when element.TryGetInt32(out var int32Value) => int32Value,
            JsonValueKind.Number when element.TryGetInt64(out var int64Value) => int64Value,
            JsonValueKind.Number when element.TryGetDecimal(out var decimalValue) => decimalValue,
            JsonValueKind.Number when element.TryGetDouble(out var doubleValue) => doubleValue,
            JsonValueKind.True => true,
            JsonValueKind.False => false,
            JsonValueKind.Null => null,
            _ => element.GetRawText()
         };
      }
   }
}
